Fix get_line_table method
Summary:
Attempt to use `get_line_table()` method fails with error:
  File "...#link-tree/dex.py", line 706, in get_line_table
  op = op_args[0]
  TypeError: 'debug_info_op' object does not support indexing

Reviewed By: danzimm

Differential Revision: D14325000

fbshipit-source-id: de7a91eef2288a78a9c602280f47855cd682681d