fix travis ci (#392)
Summary:
Pull Request resolved: https://github.com/facebook/redex/pull/392

Travis CI has been failing. It looks like it's because g++ doesn't like our initializer list.
```
opt/dedup-strings/DedupStrings.cpp:501:74: error: no matching function for call to ‘std::unordered_map<DexString*, DedupStrings::DedupStringInfo>::insert(<brace-enclosed initializer list>)’
     strings_to_dedup.insert({s, {duplicate_string_loads, dexes_to_dedup}});
```

Reviewed By: minjang

Differential Revision: D14795405

fbshipit-source-id: 4525d39d73606895f2b8d787ea85e02dd48e8ae9