Fix compilation
Summary:
Redex is unable to compile due to strict warning (function did not override base class virtual function).

```
In file included from native/redex/opt/type-erasure/TypeErasurePass.cpp:16:
native/redex/opt/type-erasure/TypeErasureInterDexPlugin.h:39:8: error: 'add_to_scope' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]
  void add_to_scope(DexClass* cls) { m_scope.push_back(cls); }
       ^
native/redex/opt/interdex/InterDexPassPlugin.h:29:16: note: overridden virtual function is here
  virtual void add_to_scope(DexClass* cls) {}
               ^
1 error generated.
```

Reviewed By: yuxuanchen1997

Differential Revision: D14890589

fbshipit-source-id: 84595ce636816381bb8b3103c6dba32af549f665